name: Container CI
on:
  push:
  pull_request:

defaults:
  run:
    working-directory: ./

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Generate docs (demo)
        run: |
          make ai-dev <<EOF
          Demo product now
          Users; pain1, pain2, pain3
          Speed with quality
          - Goal1
          - Goal2
          Budget 10k; 6 months; web+mobile
          None
          Risk1; Risk2; Risk3
          Assumption1; Assumption2
          MVP in 1 city
          EOF
          make prd
      - name: Verify suite
        run: make verify-outputs
      - name: Pack artifacts
        run: zip -qr artifacts.zip docs
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-suite
          path: artifacts.zip
          retention-days: 90
