name: Container CI
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:

permissions:
  contents: read
  packages: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Container CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Read BMAD version
        id: ver
        run: echo "image=$(cat .bmad-version)" >> $GITHUB_OUTPUT

      - name: Pull BMAD image
        run: docker pull "${{ steps.ver.outputs.image }}"

      - name: Generate PRD via vibe-prd wrapper
        run: make prd

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: prd-docs
          path: docs/