name: Repository CI
on:
  push:
  pull_request:

defaults:
  run:
    working-directory: ./

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify repository structure
        run: make verify
      - name: Check template count
        run: |
          template_count=$(find professional-templates -name "*.md" -type f | wc -l)
          echo "Found $template_count templates"
          if [ $template_count -lt 20 ]; then
            echo "❌ Expected at least 20 templates, found $template_count"
            exit 1
          fi
      - name: Display repository tree
        run: make tree