name: Container CI
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:

permissions:
  contents: read
  packages: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  # force lowercase image name for GHCR
  IMAGE_OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Normalize image ref to lowercase
        id: img
        run: |
          echo "OWNER_LC=${IMAGE_OWNER,,}" >> $GITHUB_OUTPUT
          echo "NAME_LC=${IMAGE_NAME,,}" >> $GITHUB_OUTPUT

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (PRs) / Build+Push (tags)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ghcr.io/${{ steps.img.outputs.OWNER_LC }}/${{ steps.img.outputs.NAME_LC }}:${{ github.sha }}
            ${{ startsWith(github.ref, 'refs/tags/') && format('ghcr.io/{0}/{1}:{2}', steps.img.outputs.OWNER_LC, steps.img.outputs.NAME_LC, github.ref_name) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Smoke test image
        run: |
          echo "🧪 Testing container functionality..."
          # Test basic commands
          docker run --rm ghcr.io/${{ steps.img.outputs.OWNER_LC }}/${{ steps.img.outputs.NAME_LC }}:${{ github.sha }} make help
          docker run --rm ghcr.io/${{ steps.img.outputs.OWNER_LC }}/${{ steps.img.outputs.NAME_LC }}:${{ github.sha }} make status

          # Test document creation (the core functionality)
          echo "🧪 Testing document creation..."
          mkdir -p test-workspace
          docker run --rm \
            -v "$PWD/test-workspace":/workspace \
            -w /workspace \
            ghcr.io/${{ steps.img.outputs.OWNER_LC }}/${{ steps.img.outputs.NAME_LC }}:${{ github.sha }} \
            bash -c "WORKSPACE=/workspace make -C /app create T=create-prd.md N=test-prd.md"

          # Verify file was created
          if [ -f "test-workspace/test-prd.md" ]; then
            echo "✅ Document creation works"
            echo "📄 Created file contents (first 3 lines):"
            head -3 test-workspace/test-prd.md
          else
            echo "❌ Document not created"
            echo "📁 Workspace contents:"
            ls -la test-workspace/
            exit 1
          fi