name: release
on:
  push:
    tags:
      - "v*"

jobs:
  cut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Build suite for release
        run: make release-check

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-suite
          path: artifacts.zip
          retention-days: 90

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: vibe-prd ${{ github.ref_name }}
          generateReleaseNotes: true
          artifacts: artifacts.zip
          artifactContentType: application/zip
          body: |
            Outputs:
            - BMAD natives → docs/bmad/
            - 22 pro docs → docs/templates/
            Guardrails: no-sudo, UID/GID safe, CI-verification.
