name: Release
on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Build suite for release
        run: make release-check
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-suite
          path: artifacts.zip
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: vibe-prd ${{ github.ref_name }}
          generateReleaseNotes: true
          artifacts: artifacts.zip
          artifactContentType: application/zip
          body: |
            Outputs:
            - BMAD natives → docs/bmad/
            - 22 pro docs → docs/templates/
            Auto-updated BMAD via Renovate; digest locked for reproducibility.