name: release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute tags
        id: meta
        run: |
          REF="${GITHUB_REF#refs/tags/}"
          IMAGE="ghcr.io/${GITHUB_REPOSITORY##*/}"
          # force repo owner namespace
          IMAGE="ghcr.io/${GITHUB_REPOSITORY_OWNER}/ai-dev-tasks"
          echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
          echo "VERSION=${REF#v}" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.VERSION }}
            ${{ steps.meta.outputs.IMAGE }}:latest