name: Release
on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Build suite for release
        run: make release-check
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-suite
          path: artifacts.zip
      - name: Create GitHub Release with asset
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts.zip
          generate_release_notes: true
        with:
          files: artifacts.zip
          generate_release_notes: true
