name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "17 9 * * *" # daily 09:17 America/Chicago

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: info