name: Template Validation

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ] || [ -f package.json ]; then
            npm ci || npm install
          fi

      - name: Verify templates
        run: |
          if make -q verify 2>/dev/null; then
            make verify
          elif [ -f scripts/verify-enterprise-output.mjs ]; then
            node scripts/verify-enterprise-output.mjs --mode=templates
          elif [ -f scripts/template-validation.mjs ]; then
            node scripts/template-validation.mjs
          else
            echo "No validation script found"; exit 1
          fi
